import time

import pyautogui as py

screenWidth, screenHeight = py.size()
currentMouseX, currentMouseY = py.position()
py.moveTo(100, 150)
link = py.prompt("Qual destino da pasta RPA - Artigo")
py.hotkey('win', 'e')
py.moveTo(x=714, y=756)
py.hotkey('win', 'up')
py.hotkey('Ctrl', 'l')
time.sleep(2)
py.write(link)
py.hotkey('enter')
time.sleep(2)
page = py.prompt("Qual a numeração da página à ser modificada?")
time.sleep(3)
py.moveTo(x=1000, y=200)
py.leftClick()
time.sleep(3)
if len(page) == 1:
    py.write(page + '_')
    py.hotkey('Enter')
else:
    py.write(page)
    py.hotkey('Enter')
time.sleep(10)
py.hotkey('Shift', 'Ctrl', 'S')
time.sleep(8)
py.hotkey('Enter')
time.sleep(7)
py.hotkey('Ctrl', 'c')
time.sleep(2)
py.hotkey('Backspace')
time.sleep(2)
py.write("Página {} - Modificado.pdf".format(page))
time.sleep(2)
py.hotkey('Enter')
time.sleep(5)
py.hotkey('win')
time.sleep(3)
py.write('Excel')
time.sleep(2)
py.hotkey('Enter')
time.sleep(5)
py.hotkey('Ctrl', 'n')
time.sleep(1)
py.hotkey('tab')
time.sleep(1)
py.hotkey('Enter')
time.sleep(5)
py.write('Nome do Documento')
py.hotkey('Right')
py.write('Status')
py.hotkey('Down')
py.write('Documento alterado')
py.hotkey('left')
py.hotkey('Ctrl', 'v')
time.sleep(2)
py.hotkey('F12')
time.sleep(2)
py.hotkey('Backspace')
time.sleep(2)
py.write('Relatório de execução')
time.sleep(5)
py.hotkey('Ctrl', 'l')
time.sleep(2)
py.write(link)
time.sleep(2)
py.hotkey('Enter')
py.moveTo(x=506, y=474)
py.click(button='left', clicks=1)
